baseURL = 'https://victorcosta.dev/'
languageCode = 'en-us'
title = 'Victor Costa'
theme = 'ananke'

[[menu.main]]
    name = "Blog"
    url = "/posts/"
    weight = 10

# [[menu.main]]
#     name = "TIL"
#     url = "/til/"
#     weight = 20

[[menu.main]]
    name = "About"
    url = "/about/"
    weight = 30
